# Generated by Django 5.2.9 on 2025-12-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
