# Generated by Django 6.0 on 2026-01-18 10:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_challenge_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='max_attempts',
            field=models.PositiveIntegerField(default=0, help_text='0 = Infinity'),
        ),
    ]
