# Generated by Django 6.0 on 2026-01-18 10:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_challenge_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='max_attempts',
            field=models.PositiveIntegerField(default=0, help_text='0 = безлимитно'),
        ),
    ]
