# Generated by Django 6.0 on 2026-01-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_challenge_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='max_attempts',
            field=models.PositiveIntegerField(default=0, help_text='0 = infinity'),
        ),
    ]
