# Generated by Django 6.0 on 2026-01-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(blank=True, help_text='Time when the main lesson ends', null=True)),
                ('hard_deadline', models.DateTimeField(blank=True, help_text='Final blocking time (including delay)', null=True)),
            ],
        ),
    ]
