# Generated by Django 6.0 on 2026-01-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsettings',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Time when the lesson started', null=True),
        ),
    ]
